/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssinaturasRouteImport } from './routes/assinaturas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as ApiPublicMisticpayRouteImport } from './routes/api/public/misticpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturasRoute = AssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMisticpayRoute = ApiPublicMisticpayRouteImport.update({
  id: '/api/public/misticpay',
  path: '/api/public/misticpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinaturas': typeof AssinaturasRoute
  '/auth': typeof AuthRoute
  '/site/$slug': typeof SiteSlugRoute
  '/api/public/misticpay': typeof ApiPublicMisticpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinaturas': typeof AssinaturasRoute
  '/auth': typeof AuthRoute
  '/site/$slug': typeof SiteSlugRoute
  '/api/public/misticpay': typeof ApiPublicMisticpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinaturas': typeof AssinaturasRoute
  '/auth': typeof AuthRoute
  '/site/$slug': typeof SiteSlugRoute
  '/api/public/misticpay': typeof ApiPublicMisticpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/assinaturas' | '/auth' | '/site/$slug' | '/api/public/misticpay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assinaturas' | '/auth' | '/site/$slug' | '/api/public/misticpay'
  id:
    | '__root__'
    | '/'
    | '/assinaturas'
    | '/auth'
    | '/site/$slug'
    | '/api/public/misticpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinaturasRoute: typeof AssinaturasRoute
  AuthRoute: typeof AuthRoute
  SiteSlugRoute: typeof SiteSlugRoute
  ApiPublicMisticpayRoute: typeof ApiPublicMisticpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinaturas': {
      id: '/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/misticpay': {
      id: '/api/public/misticpay'
      path: '/api/public/misticpay'
      fullPath: '/api/public/misticpay'
      preLoaderRoute: typeof ApiPublicMisticpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinaturasRoute: AssinaturasRoute,
  AuthRoute: AuthRoute,
  SiteSlugRoute: SiteSlugRoute,
  ApiPublicMisticpayRoute: ApiPublicMisticpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
